### ISSUE TITLE
Clarify the meta-data storage pattern

### ISSUE THREAD

**Issue by vermorel** [Evernest/Evernest#20]
There are multiple meta-data to be persisted such as:

* Who opened a new account and when.
* Who created a stream and when.
* Who changed the access rights and when.
* Etc.

I would suggest to store all those data as _events_ within a `system` stream within Evernest itself.

**Comment by eliemichel** [comment]
@raphaelrieuhelft @dianegalloiswong It should be documented somewhere. In README.md for example.
