### ISSUE TITLE
Upgrade to MVC 5 and Razor 3

### ISSUE THREAD

**Issue by vermorel** [Evernest/Evernest#26]
I would suggest to upgrade to the latest version of MVC, see http://www.asp.net/mvc/mvc5 and consequently to upgrade toward Razor 3 as well.

How to upgrade: http://www.asp.net/mvc/overview/releases/how-to-upgrade-an-aspnet-mvc-4-and-web-api-project-to-aspnet-mvc-5-and-web-api-2

**Comment by apiot** [comment]
Done
