### ISSUE TITLE
Azure Container names should be lowercase

### ISSUE THREAD

**Issue by raphaelrieuhelft** [Evernest/Evernest#37]
Azure Storage Emulator sends an Error 400 ("Bad Request") on some tests. Container names such as "streamIndex" should contain only lowercase letters per Azure naming rules : http://msdn.microsoft.com/en-us/library/azure/dd135715.aspx

**Comment by Bromind** [comment]
Acknoledge, but I have no-time to manage it right now (cause compiler project sunday :-) )

**Comment by Olxinos** [comment]
closed, it's now streamindex (should have been solved a month ago, but i didn't push, sorry)
