### ISSUE TITLE
Remove 'Main' class from EvernestBack

### ISSUE THREAD

**Issue by vermorel** [Evernest/Evernest#49]
The `EvernestBack` looks like a library assembly. I suggest to remove the `Main` class that is making the situation looks confuse.

**Comment by Olxinos** [comment]
It is currently used to test the back.

**Comment by eliemichel** [comment]
@Olxinos You could use a separate test using `EvernestBack` as a library.

**Comment by Olxinos** [comment]
Alexis211 did it and created a project dedicated to unit tests (thanks!), so i close it since he hasn't yet..
