### ISSUE TITLE
Design of WriteLocker is odd

### ISSUE THREAD

**Issue by vermorel** [Evernest/Evernest#52]
The class `WriteLocker` is odd. The method `Store()` starts a thread too. Naming of both class and methods is poor. I am not too sure to understand its purpose too.

**Comment by Olxinos** [comment]
This class no longer exists, though they are replaced by equally poor named classes (WorkerThread<TJob, TQuery, TAnswer>, WriterJob and ReaderJob, the first one is a host class, the second and third two strategies).
The purpose of those classes is to implement a message queue which will handle the messages asynchronously (plus make sure all the push calls to the same stream are done in the same thread).
