### ISSUE TITLE
IAgent, poor name, poor design

### ISSUE THREAD

**Issue by vermorel** [Evernest/Evernest#53]
According to the inline doc, the `IAgent` is supposed to represent a transaction; thus, the naming is really off. An _agent_ should be reserved to something that _acts_ and do something, not merely be a contract of some kind.

**Comment by vermorel** [comment]
The `Agent` implementation seems to be some kind of (de)serializer instead. No relation with any kind of agent.

**Comment by Olxinos** [comment]
This class no longer exists. It has been replaced by the (equally poorly) named CallbackDecorator<TQuery, TAnswer> (it isn't really a decorator, it extends TQuery with a success and failure callback, but it doesn't inherit from TQuery) and LowLevelEvent (mostly a pair (message, id) with a serialization method, well the "agent" without the callback).
