### ISSUE TITLE
Add 'ReadMe.md' to every assembly

### ISSUE THREAD

**Issue by vermorel** [Evernest/Evernest#57]
Every assembly (aka project) should have its own `ReadMe.md` file to outline the purpose of the project, and the most salient design aspects. Folders should also have `ReadMe.md` of their own if their purpose is non-trivial.

**Comment by eliemichel** [comment]
8c43494 fixes it for EvernestWeb.

**Comment by Bromind** [comment]
I complete EvernestBack with what I did but didn't push.
