### ISSUE TITLE
AccessRight should be treated as a contract

### ISSUE THREAD

**Issue by vermorel** [Evernest/Evernest#70]
The enumeration `AccessRight` is de-facto a contract because it is used for contract properties. Thus, the enumeration should be moved to the contract folder. Then, in order to avoid surprises when (de)serializing, I strongly suggest to assign the enumeration values by default, see http://msdn.microsoft.com/en-us/library/cc138362.aspx

**Comment by raphaelrieuhelft** [comment]
The same goes for AccessAction, and FrontError once we keep track of some of them in a stream
