### ISSUE TITLE
EvernestBack.EventStream.Size is not accurate upon restart

### ISSUE THREAD

**Issue by raphaelrieuhelft** [Evernest/Evernest#79]
When getting an existent EventStream after a restart, its Size property is reset to 0 instead of being set to its pre-shutdown value. This makes Pull operations inaccurate.

**Comment by Olxinos** [comment]
There was indeed a bug (a +1 missing somewhere) but nothing like a complete reset, is it deterministic? Did you push exactly one element before existing?

**Comment by raphaelrieuhelft** [comment]
I have a stream with ~50 events on it when I browse it with the Server view of Visual Studio. When I restart, I attempt to pull all the events with a call to PullRange from 0 to backStream.Size, and I receive exactly the oldest event of the stream.

**Comment by raphaelrieuhelft** [comment]
To add on this, while the Size property is at 0, I do get a list of eleven events if I call PullRange from 0 to 10 (arbitrarily) but if I call it from 0 to 100, PullRange fails (rightfully so, as there are only ~50 events).

**Comment by raphaelrieuhelft** [comment]
Seems fixed by our commits from today, closing.
